package org.user.util;

public class Constants {
    public static final String CREATED = "Created successfully.";
    public static final String ACTIVATED = "Activated successfully.";
    public static final String DE_ACTIVATED = "De-activated successfully.";
    public static final String REMOVED = "Removed successfully.";
    public static final String VALID_TOKEN = "Token is validated.";
    public static final String CREDENTIALS_MISMATCH = "Credentials mismatch, please re-check your username and password.";
    public static final String RETRIEVED = "Retrieved successfully.";
    public static final String REGEX_MISS_MATCH = "Invalid email format.";
    public static final String UPDATED = "Updated successfully";
    public static final String NOT_FOUND = "Data not found";
    public static final String SUCCESS = "Request successful";
    public static final String FOUND = "Data Found";
    public static final String DELETED = "Deleted Successfully";
    public static final String DATA_NULL = "No Data found";
    public static final String IDDOESNOTEXIST = "Id does not exist";
    public static final String EMAIL_PATTERN = "^[a-za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    public static final String PHONE_PATTERN = "/^(?:(?:\\+|0{0,2})91(\\s*|[\\-])?|[0]?)?([6789]\\d{2}([ -]?)\\d{3}([ -]?)\\d{4})$/";
    public static final String EMAIL = "Already Exist Email Id";
    public static final String PHONE = "Already Exist Phone No";
    public static final String User = " Id does not exist";
    public static final String REQUEST = "Request successful";
    public static final String ORGANIZATIONID = "Organization Id does not exist";
    public static final String CENTERID = "Center Id does not exist";
    public static final String SPORTSID = "Sport Id does not exist";
    public static final String SPORTSCENTER = "Sport Center Id does not exist";
    public static final String ISEMPTY = "Please upload a valid CSV file";
    public static final String SUCCESSFULLYCSV = "CSV uploaded and inserted into database successfully!";
    public static final String ERRORCSV = "Error uploading CSV";
    public static final String BODY = "Welcome to ABC Sports! You have successfully logged in. Enjoy exploring our sports features and services.";
    public static final String SUBJECT = "SUCCESSFULLY LOGIN THE ABC SPORTS";
    public static final String IMAGEID = "IMAGE ID NOT EXISTS";
    public static final String ENDCREATED = "/api/user/v1/create";
    public static final String ENDRETRIEVE = "/api/user/v1/retrieve";
    public static final String CREATED_USER = "CREATED";
    public static final String CREATE = "CREATE";
    public static final String UPDATE = "UPDATE";
    public static final String RETRIEVE = "RETRIEVE";
    public static final String REOMVE = "REMOVE";
    public static final String USER = "USER";
    public static final String USERREQUESTEXCEPTION = "USERREQUESTEXPTIONNOTFOUND";
    public static final String POST = "POST";
    public static final String GET = "GET";
    public static final String PUT = "PUT";
    public static final String LOGIN = "LOGIN";
    public static final String DELETE = "DELETE";
    public static final String BOOKINGID = "BOOKING ID NOT EXISTS";
    public static final Integer ORGANIZATION = 2;
    public static final Integer SPORT = 4;
    public static final Integer CENTER = 3;
    public static final Integer IMAGE = 5;
    public static final Integer SPORTCENTERMAP = 6;
    public static final Integer BOOKING = 7;

}